variable "creation_token" {
    description = "(Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See [Elastic File System] (http://docs.aws.amazon.com/efs/latest/ug/) user guide for more information."
    default = null
}

variable "encrypted" {
    description = "(Optional) If true, the disk will be encrypted."
    default = false
}

variable "kms_key_id" {
    description = "(Optional) The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true."
    default = null
}

variable "lifecycle_policy" {
    description = "(Optional) A file system lifecycle policy object (documented below)."
    default = null
}

variable "performance_mode" {
    description = " (Optional) The file system performance mode. Can be either generalPurpose or maxIO (Default: generalPurpose)."
    default = null
}

variable "provisioned_throughput_in_mibps" {
    description = "(Optional) The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned."
    default = null
}

variable "throughput_mode" {
    description = "(Optional) Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned. When using provisioned, also set provisioned_throughput_in_mibps."
    default = null
}

variable "tags" {
    description = "(Optional) A map of tags to assign to the file system."
    default = null
}

